apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.prod.svc.cluster.local:9090
        isDefault: true
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger.prod.svc.cluster.local:16686
        uid: jaeger
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.prod.svc.cluster.local:3100
        jsonData:
          derivedFields:
            - datasourceUid: jaeger
              matcherRegex: "trace_id\":\"([a-f0-9]+)\""
              name: TraceID
              url: "$${__value.raw}"
            - datasourceUid: jaeger
              matcherRegex: "trace_id\":\"([a-f0-9]+)\""
              name: View in Jaeger
              url: "http://localhost:16686/trace/$${__value.raw}"
