apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: kong-patch.yaml
  - path: prometheus-patch.yaml
  - path: payment-service-patch.yaml

images:
  - name: auth-service
    newName: yourdockerhub/auth-service
    newTag: "latest"
  - name: inventory-service
    newName: yourdockerhub/inventory-service
    newTag: "latest"
  - name: order-service
    newName: yourdockerhub/order-service
    newTag: "latest"
  - name: payment-service
    newName: yourdockerhub/payment-service
    newTag: "latest"
