apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  labels:
    app: payment-service
data:
  OTEL_SERVICE_NAME: "payment-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.infra.svc.cluster.local:4318"
  AUTH_SERVICE_URL: "http://auth-service.staging.svc.cluster.local:3000"
