apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app: auth-service
data:
  OTEL_SERVICE_NAME: "auth-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.infra.svc.cluster.local:4318"
