apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    services:
      - name: auth-service
        url: http://auth-service.staging.svc.cluster.local:3000
        routes:
          - name: auth-route
            paths:
              - /auth
            strip_path: true
      - name: inventory-service
        url: http://inventory-service.staging.svc.cluster.local:3000
        routes:
          - name: inventory-route
            paths:
              - /items
            strip_path: false
      - name: order-service
        url: http://order-service.staging.svc.cluster.local:3000
        routes:
          - name: order-route
            paths:
              - /orders
            strip_path: false
      - name: payment-service
        url: http://payment-service.staging.svc.cluster.local:3000
        routes:
          - name: payment-route
            paths:
              - /payments
            strip_path: false
