apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:
  - path: kong-patch.yaml
  - path: prometheus-patch.yaml
  - path: payment-service-patch.yaml
  - path: auth-service-config-patch.yaml
  - path: inventory-service-config-patch.yaml
  - path: order-service-config-patch.yaml
  - path: grafana-service-patch.yaml
  - path: jaeger-service-patch.yaml
  - path: prometheus-service-patch.yaml

images:
  - name: auth-service
    newName: hungnv2511/auth-service
    newTag: "5297c76"
  - name: inventory-service
    newName: hungnv2511/inventory-service
    newTag: "5297c76"
  - name: order-service
    newName: hungnv2511/order-service
    newTag: "5297c76"
  - name: payment-service
    newName: hungnv2511/payment-service
    newTag: "5297c76"
