apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:
  - path: kong-patch.yaml
  - path: prometheus-patch.yaml
  - path: payment-service-patch.yaml
  - path: auth-service-config-patch.yaml
  - path: inventory-service-config-patch.yaml
  - path: order-service-config-patch.yaml
  # Local testing: change NodePort services to ClusterIP
  - target:
      kind: Service
      name: grafana
    patch: |
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
  - target:
      kind: Service
      name: jaeger
    patch: |
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
  - target:
      kind: Service
      name: prometheus
    patch: |
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: remove
        path: /spec/ports/0/nodePort
  # Kong: increase memory limit for local K8s
  - target:
      kind: Deployment
      name: kong
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi

images:
  - name: auth-service
    newName: hungnv2511/auth-service
    newTag: "5297c76"
  - name: inventory-service
    newName: hungnv2511/inventory-service
    newTag: "5297c76"
  - name: order-service
    newName: hungnv2511/order-service
    newTag: "5297c76"
  - name: payment-service
    newName: hungnv2511/payment-service
    newTag: "5297c76"
