apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-config.yml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      otlp/jaeger:
        endpoint: jaeger.staging.svc.cluster.local:4317
        tls:
          insecure: true
      otlphttp/loki:
        endpoint: http://loki.staging.svc.cluster.local:3100/otlp

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/jaeger]
        logs:
          receivers: [otlp]
          exporters: [otlphttp/loki]
